UPDATE `preguntas` SET `preguntas` = '1. Se cuenta con una visión omnicanal orientada al cliente.|\r\n2. Los clientes pueden acceder a soporte e información y herramientas para auto- configuración del servicio disponibles a través de todos los canales.|\r\n3. La experiencia del cliente y el uso de datos se recopilan rutinariamente a través de todos los canales y se comparten a través de las funciones organizacionales (p.e. gestión de producto, soporte al cliente, operaciones de red).|\r\n4. El cliente puede combinar nuevos servicios digitales con servicios tradicionales.|\r\n5. La gestión de la experiencia del cliente se ha movido de reactiva a proactiva e incluye acciones automatizadas (p.e. la siguiente mejor acción, ofertas personalizadas).|\r\n6. La analítica de datos está siendo extensamente usada para mejorar el valor del cliente, incluyendo el desarrollo de ofertas de nuevos servicios, ofertas y marca).|\r\n7. Las herramientas digitales y los sistemas están habilitando la personalización de servicios incluyendo productos de terceros.|\r\n8. El cliente participa activamente en el diseño de nuevos productos/servicios a través de plataformas de innovación abierta.' WHERE `preguntas`.`id_pregunta` = 1;

UPDATE `preguntas` SET `preguntas` = '1. Se conocen los diferenciadores de la marca y del negocio|\r\n2. La empresa conoce sus competidores directos, indirectos y sustitutos, conoce como manejan sus experiencias digitales.|\r\n3. Se desarrollan actividades promocionales de la marca, productos y servicios en medios digitales|\r\n4. La Marca presenta la misma consistencia en todos los canales digitales|\r\n5. Se conocen datos de los clientes (edades, sexo) y se enfocan los contenidos en estas variables|\r\n6. Se analizan obtiene información de datos sociodemográficos que alimenten las campañas de marketing |\r\n7. Se conocen los atributos de la marca y son comunicados al cliente  ' WHERE `preguntas`.`id_pregunta` = 5;

UPDATE `preguntas` SET `preguntas` = '1. Se han aprobado inversiones formales alineadas a la estrategia digital.|\r\n2. Se han definido objetivos digitales en el presupuesto de la compañía|\r\n3. Se han aprobado inversiones para iniciativas de transformación digital.|\r\n4. Se realiza una medición de los ingresos por productos digitales.|\r\n5. La empresa capitaliza su inversión previa y genera nuevos ingresos basados en capacidades digitales y modelos de negocio digitales.|\r\n6. Los ingresos por negocios digitales permiten una inversión constante en nuevas iniciativas digitales.|\r\n7. Se cuenta con datos relacionados con los ingresos para determinar la contribución porcentual de las ventas digitales del total de ingresos de la empresa' WHERE `preguntas`.`id_pregunta` = 7;

UPDATE `preguntas` SET `preguntas` = '1. Se cuenta con modelos de negocio que aceleren la entrada a nuevos mercados digitales y acceder a nuevos clientes|\r\n2. Se conoce la experiencia de vida que obtienen los clientes al usar los productos o servicios |\r\n3. Se conoce el significado real de los productos o servicios de la empresa para las personas   |\r\n4. Se conoce la distribución de ingresos por lineas o familias de productos o servicio|\r\n5. ¿Los clientes, comparten sus experiencias con la marca, en redes sociales?|\r\n6. ¿Se determinan los criterios que se deben evaluar para incursionar en nuevos mercados?|\r\n7. ¿Se han establecido perfiles de clientes acordes a las necesidades del negocio?, y se comprenden sus características|\r\n8. ¿Se realiza investigación de mercados?|\r\n9. ¿Se conoce el costo de captar y gestionar un cliente nuevo y de fidelizar actuales?|\r\n10. Se han identificado los segmentos de clientes y la rentabilidad de los mismos por cada segmento ' WHERE `preguntas`.`id_pregunta` = 8;

UPDATE `preguntas` SET `preguntas` = '1. Se mide la participación de las acciones digitales en los ingresos totales de la empresa|\r\n2. Se conoce cómo los productos o servicios crean valor para los clientes y empleados|\r\n3. ¿Analizamos regularmente nuestro modelo de negocio para buscar oportunidades de mejora e innovación?|\r\n4. ¿Analizamos regularmente nuestra curva de valor para buscar oportunidades de innovación y diferenciación?|\r\n5. ¿El equipo comercial trabaja en la búsqueda de oportunidades o generación de ideas de innovación aplicables a productos, servicios o soluciones?|\r\n6. ¿Dentro de las iniciativas de innovación se ha trabajado en el desarrollo y sofisticación de productos o servicios?|\r\n7. ¿La empresa cuenta con un sistema de gestión de innovación?, o se han planteado retos a nivel de innovación ' WHERE `preguntas`.`id_pregunta` = 9;

UPDATE `preguntas` SET `preguntas` = '1. Se están implementado tecnologías analíticas para facilitar la recolección y compartición de datos a través de las funciones.|\r\n2. Se están usando tecnologías analíticas para la optimización de procesos y servicios.|\r\n3. Las tecnologías como el análisis avanzado de datos respaldan los procesos de innovación en toda la empresa, desde el desarrollo de nuevos servicios hasta la garantía del servicio y la atención al cliente.|\r\n4. Los sistemas de información actuales (de gestión y relaciones con el cliente) permiten obtener información en tiempo real y conectada con otras plataformas para agilizar operaciones|\r\n5. Se recopila información o datos acerca del desempeño de los procesos y comportamiento de los clientes|\r\n6. ¿Se depuran o realiza la limpieza de los datos antes de ser utilizados?|\r\n7. ¿Se aseguran que no exista información o datos duplicada o incompleta en cuanto a clientes y resultados de los procesos?' WHERE `preguntas`.`id_pregunta` = 14;

UPDATE `preguntas` SET `preguntas` = '1. Los procesos a lo largo de la empresa están alineados a la arquitectura digital.|\r\n2. La automatización en toda la empresa impulsa un rendimiento superior comparada con otros pares de la industria.|\r\n3. Se cuenta con estructura y configuración de red que agilice la captación y procesamiento de datos|\r\n4. ¿La compañía cuenta con herramientas que permitan el trabajo remoto sin interrumpir operaciones?|\r\n5. Se conoce el inventario de equipos de tecnología (incluyendo la móvil)|\r\n6. Se cuenta con sistemas de información y/o tecnologías CRM ERP para apoyar las labores comerciales fuera de la oficina' WHERE `preguntas`.`id_pregunta` = 16;

UPDATE `preguntas` SET `preguntas` = '1. Se cuenta con una arquitectura IT digital específica que soporte la operación de los procesos |\r\n2. Se ha definido un plan de transformación de arquitectura de IT|\r\n3. Se ha definido los cambios requeridos están en ejecución para alcanzar la arquitectura objetivo. Los planes de inversión en IT están alineados con la arquitectura objetivo|\r\n4. Se cuenta con un proceso para evaluar las inversiones en IT basado en su alineación con la estrategia digital de la empresa|\r\n5. Se ha implementado la arquitectura IT digital, incluyendo la consolidación de sistemas en plataformas para soportar omni-canales y servicios de terceros|\r\n6. Se ha implementado procesos end-to-end que soportan servicios digitales mediante el aprovechamiento de la arquitectura IT digital' WHERE `preguntas`.`id_pregunta` = 18;

UPDATE `preguntas` SET `preguntas` = '1. La empresa ha dado a conocer al los objetivos de transformación digital a los distintos grupos de trabajo|\r\n2. Se cuentan con despliegue de servicios digitales con enfoque en mejoras incrementales en los distintos procesos|\r\n3. Se cuenta con una estructura de liderazgo distribuido y se fomenta el trabajo colaborativo|\r\n4. Hay comunicación continua desde la Gerencia acerca de la estrategia digital y los avances en su implementación.|\r\n5.  Se  han  organizado  equipos  multifuncionales  bajo  la  guía  de  líderes  que establecen las pautas de alto nivel que se pueden aplicar.|\r\n6. Los sistemas de rendimiento y de compensación incorporan elementos digitales a través de la empresa.|\r\n7. Se permite a los empleados ejercer un rol de liderazgo para tomar decisiones significativas de forma transparente.|\r\n8. La colaboración con otros socios está bien establecida, la generación de innovación de servicios está por delante de la competencia.|\r\n9. La empresa es flexible y se adapta fácilmente a los cambios en el mercado de una manera más ágil que sus competidores priorizando la experiencia del cliente.\r\n\r\n' WHERE `preguntas`.`id_pregunta` = 19;

UPDATE `preguntas` SET `preguntas` = '1. Se cuenta con recursos (personas, tecnologícos, económicos) para apoyar el desarrollar del plan de digitalización|\r\n2. La empresa tiene una visión de la transformación digital que busca mano de obra digitalmente inteligente.\r\n' WHERE `preguntas`.`id_pregunta` = 20;

UPDATE `preguntas` SET `preguntas` = '1. Se utilizan tecnologías como analítica de datos para alimentar las métricas y KPI que apoyen los controles de los procesos y faciliten la toma de decisiones.|\r\n2. Se cuenta con indicadores clave de rendimiento para medir las ventas de servicios digitales o mediante canales digitales|\r\n3. La toma de decisiones se hace basada en datos analizados en tiempo-real, se acepta el riesgo y se trabaja de forma colaborativa bajo un liderazgo distribuido.|\r\n4. Los servicios digitales y tradicionales comparten procesos y se cuenta con métricas y KPI específicos.' WHERE `preguntas`.`id_pregunta` = 22;

UPDATE `preguntas` SET `preguntas` = '1. La estrategia digital dirige el cambio de la estructura organizacional y los indicadores claves.|\r\n2. El liderazgo de la empresa tiene suficiente conocimiento y habilidad para dirigir la estrategia digital.|\r\n3. Se han identificado iniciativas para actualizar los procesos claves del negocio para soportar servicios digitales.|\r\n4. Están siendo evaluadas las inversiones para automatizar procesos claves que soporten servicios digitales.|\r\n5.  Se  han  estado  identificado  activos  claves  (p.e.  personas,  plataformas tecnológicas) que formarán la base para la transformación digital.|\r\n6.  Se  están  implementando  procesos  para  soportar  y  automatizar  servicios digitales.|\r\n7. Están siendo desplegados procesos para recopilar y analizar datos de uso del cliente.|\r\n8. Se están diseñando e implementando procesos y políticas para soportar mejor los servicios digitales en algunas áreas claves de la empresa.|\r\n9. Las inversiones en integración de capacidades facilitan la agilidad y eficiencia de los procesos.|\r\n10. Los procesos apalancan el flujo de datos a través de toda la empresa para la optimización de servicios/productos.|\r\n11. La red en tiempo real, el cliente y otros datos de uso están siendo combinados y analizados para optimizar la confiabilidad del servicio y los procesos claves.|\r\n12. Se reduce el tiempo de comercialización de nuevas propuestas de servicios o productos mediante procesos bien establecidos.|\r\n13. Los procesos son maduros y comienzan a producir innovaciones en productos y servicios digitales.|\r\n14. La empresa se enfoca en mejorar continuamente los procesos a través de la innovación y la tecnología.' WHERE `preguntas`.`id_pregunta` = 23;

UPDATE `preguntas` SET `preguntas` = '1. Se está implementando automatización de procesos end-to-end para soportar servicios digitales.|\r\n2. Los procesos automatizados están siendo optimizados para mejorar la eficiencia y reducir costos de diseño, aprovisionamiento, y soporte de servicios digitales, incluyendo servicios de socios.|\r\n3. Los procesos end-to-end automatizados garantizan flujos de datos en tiempo real a través de funciones para mejorar la planificación y la toma de decisiones.|\r\n4. ¿La empresa cuenta con procesos o estándares de trabajo en entornos digitales?|\r\n5. Los sistemas de información de la empresa generan datos en tiempo real, a lo largo de los procesos de manufactura, transformación o prestación de servicios (se cuenta con información proveniente de maquinas, equipos o procesos)|\r\n6. Se cuenta con mecanismos de identificación y medición de datos generados por procesos o iniciativas digitales|\r\n7. Se dispone de algorítmos de predicción de demanda en el proceso comercial|\r\n8. Se cuenta con sistemas capaces de capturar, almacenar, procesar y analizar datos en los procesos que agilicen y faciliten la toma de decisiones|\r\n9. Se trasladan los datos digitalizados de la operación (prestación de servicios) o de la fabricación (manufactura, transformación) a software de proyección o simulaciones|\r\n10. ¿ La empresa cuenta con procesos documentados accesibles a toda la fuerza laboral?' WHERE `preguntas`.`id_pregunta` = 24;

UPDATE `preguntas` SET `preguntas` = '1. Se usa la co-creación con los clientes y socios en la creación de nuevos servicios para reducir costos de desarrollo y avanzar en la innovación.|\r\n2. Se cuenta con una estrategia de desarrollo de personal estructurada que permita adquirir competencias digitales u operacionales que apoyen el desarrollo del negocio.|\r\n3. El personal tiene un alto compromiso y empoderamiento para moverse de forma rápida y ágil para la consecución de los objetivos digitales de la empresa.' WHERE `preguntas`.`id_pregunta` = 26;

UPDATE `preguntas` SET `preguntas` = '1. Se han hecho inversiones iniciales para desarrollar competencias digitales incluyendo programas de formación.|\r\n2. Se cuenta con personal experto (interno o externo) para desarrollar capacidades digitales.|\r\n3. Están en marcha las inversiones en el desarrollo de competencias digitales en el personal.|\r\n4. Se  están adaptando  esquemas  de compensación  y formación para alinearse  a la estrategia digital.|\r\n5. Las iniciativas digitales incorporan personas de diferentes áreas y funciones internos y externos.|\r\n6. Se están haciendo inversiones en integración y desarrollo de capacidades no sólo para habilitar, sino para acelerar y reducir los costos de la creación de servicios digitales.|\r\n7. Las competencias digitales están bien  desarrollados y las asociaciones se forman continuamente para acceder a nuevas competencias.|\r\n8. Las competencias digitales están embebidas en toda la empresa y hace la diferencia de sus competidores.' WHERE `preguntas`.`id_pregunta` = 27;